### ISSUE TITLE
Default ROM directory

### ISSUE THREAD

**Issue by currall** [wavemotion-dave/A7800DS#1]
Is there a way to set the default directory for roms? Every time i close and reopen the emulator is resets to the root directory of my sd card

**Comment by wavemotion-dave** [comment]
Hey Scott.

No, currently that’s not a feature but it could be added fairly easily.
I keep my games in a ‘roms’ folder right off the root so it’s fast in my case but I can see where others would rather set a default directory. I’ll look into adding that in the future.
