### ISSUE TITLE
Pink Screen when loading Asteroids 7800

### ISSUE THREAD

**Issue by thanone2** [wavemotion-dave/A7800DS#2]
I loaded Asteroids on it earlier today but later in the day it started showing a pink screen on the top and freezing the bottom screen I tried other versions and different roms, but still, pink screen. What do I do?
(btw I'm on NDSi)

**Comment by wavemotion-dave** [comment]
Sorry to hear!  Asteroids is one of my favs - I play it often on the DSi. 

I just tried version 4.5 (my latest) and had no problems loading Asteroids. I tried the following scenarios:

- DSi running Twilight Menu++ and launching the Asteroids .a78 rom directly from the menu.
- DSi running Twilight Menu++ and launching the A7800 emulator directly and then picking Asteroids .a78 rom.
- DS running a cheap R4 clone card (not Twilight Menu++) and launching the emulator and selecting the .a78 rom.

I reloaded multiple times - and had no problems on any attempts.

Be sure that your a7800.bin BIOS file is available - it can be in /roms/bios, /data/bios or in the same directory as the emulator. 

Also, be sure you are running version 4.5 - it will show on the splash screen as you load the emulator.

**Comment by thanone2** [comment]
Hi! Thanks for responding, I don't have an r4 card but I used the Facebook hack to homebrew my DSi, I tried the other two scenarios and, pink screen, also I am running 4.5, and I don't have a bios folder. Where can I get the a7800.bin BIOS file?

**Comment by thanone2** [comment]
I'm using .a78 ROMs. In case that's what you were talking about .bin files.

**Comment by wavemotion-dave** [comment]
Sorry... my mistake! The emulator does not require a BIOS file except if you want to save highscores (highscore.rom).

I'm still trying to replicate your issue but I'm not having any luck. I'm also using .a78 files.

Do other 7800 games load or is it just Asteroids?

**Comment by thanone2** [comment]
no other titles load. if you need more info let me know. I tried loading the emulator from nolaunch but to no avail.

**Comment by thanone2** [comment]
the strangest thing is that I was playing it perfectly fine yesterday morning, but that evening it stopped.🤔

**Comment by wavemotion-dave** [comment]
I can't think of any reason why it would stop working. I checked in with some beta testers and they are reporting that it's still working fine after almost a year of 4.5 being released. 

Maybe try a re-install of the Emulator and the ROMs in case something got corrupted?

**Comment by thanone2** [comment]
I feel stupid, something must have been corrupted I replaced both and it started working.

**Comment by wavemotion-dave** [comment]
No worries - I'm glad it got sorted out.  I know someone some many months back found out that they had not formatted their SD card with standard 32K sectors - for the DSi, it's recommended that the SD card be formatted with the official SD Card Tool formatted direct from the SD organization which ensures this:

https://www.sdcard.org/downloads/formatter/

In any event, I'm glad you're running again!

**Comment by thanone2** [comment]
thanks!
